version: '3.8'

services:
  wsa-backend-web:
    container_name: 'wsa.backend.web'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '11131:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - wsa-backend-php
  wsa-backend-php:
    container_name: 'wsa.backend.php'
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    #command: php artisan serve --port 3000

networks:
  wsa-local-network:
    external: true
